graph TD
    A[Project-Tetris] --> B[README.md]
    A --> C[src]
    C --> D[Box.java]
    C --> E[BoxMatrix.java]
    C --> F[FallingShape.java]
    C --> G[KeyHandler.java]
    C --> H[MainBoard.java]
    C --> I[MainPanel.java]

